Manero/Models/AccountHeaderViewModel.cs
namespace Manero.Models
{
    public class AccountHeaderViewModel
    {
        public string? Title { get; set; }
        public string? BackButtonLink { get; set; }
        public bool ShowBackButton { get; set; } = true; 
    }

}

Manero/Models/ErrorViewModel.cs
namespace manero.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Manero/Models/ProductEntity.cs
using System.ComponentModel.DataAnnotations;

namespace Manero.Models;

public class ProductEntity
{
    [Key]
    public int Id { get; set; }

    public string ProductName { get; set; } = null!;

    public string ProductDescription { get; set; } = null!;


    //should have multiple images as well...
    public string? ProductImage { get; set; } 

    public decimal ProductPrice { get; set; }

    public int ProductRating { get; set; }

    public string ProductTag { get; set; } = null!;

    //Borde gå till entity
    public List<string>? Categories { get; set; } 


    //Should probably have tags, and quantity in sizes and colours later
    // and connected to Reviews ofc ^^

}

Manero/Models/ReviewModel.cs
using Manero.ViewModels;
using System.ComponentModel.DataAnnotations;

namespace Manero.Models;

public class ReviewModel
    {
    public int Id { get; set; }
    public int Rating { get; set; }
    public string CommentText { get; set; } = null!;
    public DateTime ReviewDate { get; set; }
}

Manero/Models/TrackModel.cs
namespace Manero.Models
{
    public class TrackModel
    {
        public int TrackId { get; set; }
        public string OrderNumber { get; set; }
    }
}

Manero/ViewModels/BannerViewModel.cs
namespace Manero.ViewModels;

public class BannerViewModel
{

    public string Title { get; set; } = null!;

    public string ButtonText { get; set; } = null!;

    public string ButtonLink { get; set; } = null!;

    public string FlexSide { get; set; } = null!;

}

Manero/ViewModels/CardGridViewModel.cs
using Manero.Models;

namespace Manero.ViewModels;

public class CardGridViewModel
{
    public string Title { get; set; } = null!;

    public string ButtonText { get; set; } = null!;

    public string ButtonLink { get; set; } = null!;
    
    public int CardNr { get; set; }

}

Manero/ViewModels/CheckoutViewModel.cs
namespace Manero.ViewModels
{
    public class CheckoutViewModel
    {
        public string? Comment { get; set; }
    }
}

Manero/ViewModels/NavbarViewModel.cs
namespace Manero.ViewModels;

public class NavbarViewModel
{

    //Decides to show either Burger or Arrow
    public bool Burger { get; set; } = true;

    //Decides over whether to show the cart button or not
    public bool ShoppingCart { get; set; } = true;

    //Decides over the information in the middle
    public string MiddleData { get; set; } = null!;

}

Manero/ViewModels/OrderViewModel.cs
namespace Manero.ViewModels
{
    public class OrderViewModel
    {
        public int? OrderNumber { get; set; }
        public DateTime? OrderDate { get; set; }
        public decimal? OrderTotal { get; set; }
        


        // placeholders        
        public string? OrderStatus { get; set; }
        public string? OrderItem { get; set; }
        public int? OrderItemQuantity { get; set; }
        public decimal? OrderItemPrice  { get; set; }
    }
}

Manero/ViewModels/PromoCodeViewModel.cs
namespace Manero.ViewModels
{
    public class PromoCodeViewModel
    {
        public string? ImageUrl { get; set; }
        public string? Title { get; set; }
        public int? Discount { get; set; }
        public string? ExpirationDate { get; set; }
    }
}

Manero/ViewModels/ReviewViewModel.cs
using Manero.Models;

namespace Manero.ViewModels
{
    public class ReviewViewModel
    {
        public int Rating { get; set; }

        public IEnumerable<ReviewModel>? Comments { get; set; } = null!;
        public string NewCommentText { get; set; } = null!;

    }
}

Manero/ViewModels/SearchViewModel.cs
namespace Manero.ViewModels;

public class SearchViewModel
{

    public string SearchWord { get; set; } = null!; 

}

Manero/ViewModels/TrackViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Manero.ViewModels
{
    public class TrackViewModel
    {
        [Required]
        [Display(Name = "ORDER NUMBER")]
        public string OrderNumber { get; set; }
    }
}

Manero/Controllers/BestSellersController.cs
using Manero.Models.Entities;
using Manero.Services;
using Microsoft.AspNetCore.Mvc;

namespace Manero.Controllers
{
    public class BestSellersController : Controller
    {
        
		private readonly ProductsService productsService;

        public BestSellersController(ProductsService productsService)
        {
            this.productsService = productsService;
        }




        //Views
        public IActionResult Index()
        {
            IEnumerable<ProductEntity> siteProducts = productsService.GetProducts();
            return View(siteProducts);
        }


        public IActionResult ProductFilter()
        {
            return View();
        }
    }
}

Manero/Controllers/CheckoutController.cs
using Manero.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Manero.Controllers
{
    public class CheckoutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(CheckoutViewModel viewModel)
        {
            //return order sucessful view if sucessful, otherwise return order failed view.
            return RedirectToAction("OrderFailed");
        }

        public IActionResult OrderFailed()
        {
            return View();
        }

        public IActionResult OrderSuccessful()
        {
            return View();
        }
    }
}

Manero/Controllers/HomeController.cs
using manero.Models;
using Manero.Controllers;
using Manero.Models;
using Manero.Services;
using Manero.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace manero.Controllers
{
	public class HomeController : Controller
	{
		//Services
		private readonly ILogger<HomeController> _logger;


        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


		//Views
        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}

}

Manero/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;

namespace Manero.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            //if there is products in cart return index view otherwise return CartEmpty.cshtml view
            return View();
        }

    }
}

Manero/Controllers/SignOutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Manero.Controllers
{
    public class SignOutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Manero/Controllers/TagsController.cs
using Manero.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;

namespace Manero.Controllers;

public class TagsController : Controller
{
    //Service
    private readonly TagsService tagsService;

    public TagsController(TagsService tagsService)
    {
        this.tagsService = tagsService;
    }


    //Views
    [Route("Tag/{tagName}")]
    public IActionResult TagsPage(string tagName)
    {
        var model = tagsService.GetTag(tagName);

        if (model == null)
        {
            return NotFound();
        }

        return View("TagsPage", model);
    }




}

Manero/Controllers/WelcomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Manero.Controllers
{
    public class WelcomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

     
        public IActionResult OnboardingFirst()
        {
            return View();
        }

        public IActionResult OnboardingSecond()
        {
            return View();
        }

        public IActionResult OnboardingThird()
        {
            return View();
        }
    }
}

Manero/Views/BestSellers/Index.cshtml
@using Manero.Services;


@inject TagsService tagsService

@{
    var products = tagsService.GetTopProducts();
}

@foreach (var product in await products)
{
    <h1>@product.ProductName</h1>

    <h1>@product.Price</h1>

    <p>@product.Rating</p>

    <p>@product.Id</p>



    <hr />
}



<section class="featured_products_section_v2">
    <div class="container">
        <div class="best_sellers_title">
            <a asp-controller="BestSellers" asp-action="ProductFilter"><h1><i class="fa-solid fa-filter"></i> Filters</h1></a>
            <a href="#">Sorting by <span>&#8744;</span></a>
        </div>
        <!-- Grid with autofill function -->
        <div class="big_card_grid">

            <!-- start of card -->
            <div class="product_card">
                <div class="card_top">
                    <!-- can be changed, between classes:
                            "card_tag_new, card_tag_sale and card_tag_top".
                        see the options below -->
                    <div class="card_tag"></div>
                    <img src="/static-images/stock-images/white-shoe.jpg" alt="product">
                    <div class="card_options">
                        <a href="#"><i class="fa-regular fa-heart"></i></a>
                        <a href="#"><i class="fa-regular fa-bag-shopping"></i></a>
                    </div>
                </div>
                <div class="card_bottom">
                    <div class="card_rating">
                        <div class="card_stars">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                        </div>
                        <p>(3)</p>
                    </div>
                    <div class="card_title">White Sneakers</div>
                    <div class="card_price">
                        <p>£20.9</p>
                        <p>£12.9</p>
                    </div>
                </div>
            </div>
            <!-- end of card -->

            <div class="product_card">
                <div class="card_top">
                    <div class="card_tag_sale">SALE</div>
                    <img src="/static-images/stock-images/black-shoe.jpg" alt="product">
                    <div class="card_options">
                        <a href="#"><i class="fa-regular fa-heart"></i></a>
                        <a href="#"><i class="fa-regular fa-bag-shopping"></i></a>
                    </div>
                </div>
                <div class="card_bottom">
                    <div class="card_rating">
                        <div class="card_stars">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                        </div>
                        <p>(3)</p>
                    </div>
                    <div class="card_title">Black Sneakers</div>
                    <div class="card_price">
                        <p>£20.9</p>
                        <p>£12.9</p>
                    </div>
                </div>
            </div>

            <div class="product_card">
                <div class="card_top">
                    <div class="card_tag_top">TOP</div>
                    <img src="/static-images/stock-images/white-shoe.jpg" alt="product">
                    <div class="card_options">
                        <a href="#"><i class="fa-regular fa-heart"></i></a>
                        <a href="#"><i class="fa-regular fa-bag-shopping"></i></a>
                    </div>
                </div>
                <div class="card_bottom">
                    <div class="card_rating">
                        <div class="card_stars">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                        </div>
                        <p>(3)</p>
                    </div>
                    <div class="card_title">White Sneakers</div>
                    <div class="card_price">
                        <p>£20.9</p>
                    </div>
                </div>
            </div>

            <div class="product_card">
                <div class="card_top">
                    <div class="card_tag_new">NEW</div>
                    <img src="/static-images/stock-images/white-shoe.jpg" alt="product">
                    <div class="card_options">
                        <a href="#"><i class="fa-regular fa-heart"></i></a>
                        <a href="#"><i class="fa-regular fa-bag-shopping"></i></a>
                    </div>
                </div>
                <div class="card_bottom">
                    <div class="card_rating">
                        <div class="card_stars">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                        </div>
                        <p>(3)</p>
                    </div>
                    <div class="card_title">White Sneakers</div>
                    <div class="card_price">
                        <p>£20.9</p>
                    </div>
                </div>
            </div>

            <div class="product_card">
                <div class="card_top">
                    <div class="card_tag_sale">SALE</div>
                    <img src="/static-images/stock-images/black-shoe.jpg" alt="product">
                    <div class="card_options">
                        <a href="#"><i class="fa-regular fa-heart"></i></a>
                        <a href="#"><i class="fa-regular fa-bag-shopping"></i></a>
                    </div>
                </div>
                <div class="card_bottom">
                    <div class="card_rating">
                        <div class="card_stars">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                        </div>
                        <p>(3)</p>
                    </div>
                    <div class="card_title">Black Sneakers</div>
                    <div class="card_price">
                        <p>£20.9</p>
                        <p>£12.9</p>
                    </div>
                </div>
            </div>

            <div class="product_card">
                <div class="card_top">
                    <div class="card_tag_top">TOP</div>
                    <img src="/static-images/stock-images/white-shoe.jpg" alt="product">
                    <div class="card_options">
                        <a href="#"><i class="fa-regular fa-heart"></i></a>
                        <a href="#"><i class="fa-regular fa-bag-shopping"></i></a>
                    </div>
                </div>
                <div class="card_bottom">
                    <div class="card_rating">
                        <div class="card_stars">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                        </div>
                        <p>(3)</p>
                    </div>
                    <div class="card_title">White Sneakers</div>
                    <div class="card_price">
                        <p>£20.9</p>
                    </div>
                </div>
            </div>

            <div class="product_card">
                <div class="card_top">
                    <div class="card_tag_new">NEW</div>
                    <img src="/static-images/stock-images/white-shoe.jpg" alt="product">
                    <div class="card_options">
                        <a href="#"><i class="fa-regular fa-heart"></i></a>
                        <a href="#"><i class="fa-regular fa-bag-shopping"></i></a>
                    </div>
                </div>
                <div class="card_bottom">
                    <div class="card_rating">
                        <div class="card_stars">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                        </div>
                        <p>(3)</p>
                    </div>
                    <div class="card_title">White Sneakers</div>
                    <div class="card_price">
                        <p>£20.9</p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

Manero/Views/BestSellers/ProductFilter.cshtml
<section class="top-navbar container">
    <a href="" class="less-symbol" style="color: #111111;"><i class="fa-solid fa-angle-left"></i></a>

    <h3>Filter</h3>
    <div class="shopping-bag-with-ball">
        <div class="orange-ball"><p>$0</p></div>
        <a href="" class="big-screen-symbols"><i class="fa-light fa-house-chimney"></i></a>
        <a href="" class="big-screen-symbols"><i class="fa-light fa-magnifying-glass"></i></a>
        <a href="" class="big-screen-symbols"><i class="fa-light fa-heart"></i></a>
        <a href="" class="big-screen-symbols"><i class="fa-light fa-circle-user"></i></a>
        <a href="" class="shopping-bag-symbol" style="color: #626262;"><i class="fa-light fa-bag-shopping"></i></a>
    </div>
</section>

<section class="filter-section container">
    <div class="product-size">
        <h3>Size</h3>
        <div class="sizes">
            <button>XS</button>
            <button>S</button>
            <button>M</button>
            <button>L</button>
            <button>XL</button>
            <button>XXL</button>
        </div>
    </div>
    <div class="product-color">
        <h3>Color</h3>
        <div class="product-colors">
            <button class="red"></button>
            <button class="ligt-blue"></button>
            <button class="beige"></button>
            <button class="dark-blue"></button>
            <button class="black"></button>
        </div>
    </div>
    <p class="filter-price">Price</p>
    <div class="range_container">
        <div class="sliders_control">
            <input id="fromSlider" type="range" value="10" min="0" max="500" />
            <input id="toSlider" type="range" value="30" min="0" max="500" />
        </div>
        <div class="form_control">
            <div class="form_control_container">
                <div class="form_control_container__time">$</div>
                <input class="form_control_container__time__input" type="number" id="fromInput" value="10" min="0" max="500" />
            </div>
            <div class="form_control_container">
                <div class="form_control_container__time">$</div>
                <input class="form_control_container__time__input" type="number" id="toInput" value="30" min="0" max="500" />
            </div>
        </div>
    </div>

    <div class="tick-button-categories">
        <label class="form-control">
            <input type="checkbox" name="checkbox1" />
            <p class="green-checkbox">SALE</p>
        </label>

        <label class="form-control">
            <input type="checkbox" name="checkbox2" />
            <p class="yellow-checkbox">NEW</p>
        </label>

        <label class="form-control">
            <input type="checkbox" name="checkbox3" />
            <p class="purple-checkbox">TOP</p>
        </label>
    </div>

    <div class="tag-section">
        <p>Tags</p>
        <button class="tag-button">KIDS</button>
        <button class="tag-button">SPORT</button>
        <button class="tag-button">DRESS</button>
        <button class="tag-button">PANTS</button>
        <button class="tag-button">T-SHIRT</button>
        <button class="tag-button">HAT</button>
        <button class="tag-button">UNISEX</button>
        <button class="tag-button">BAG</button>
        <button class="tag-button">ACCESSORIES</button>
        <button class="tag-button">SHOES</button>
        <button class="tag-button">POLO</button>
    </div>

    <div class="review-button container">
        <button class="black-button">APPLY FILTERS</button>
    </div>

    <script>
        function controlFromInput(fromSlider, fromInput, toInput, controlSlider) {
            const [from, to] = getParsed(fromInput, toInput);
            fillSlider(fromInput, toInput, '#C6C6C6', '#25daa5', controlSlider);
            if (from > to) {
                fromSlider.value = to;
                fromInput.value = to;
            } else {
                fromSlider.value = from;
            }
        }

        function controlToInput(toSlider, fromInput, toInput, controlSlider) {
            const [from, to] = getParsed(fromInput, toInput);
            fillSlider(fromInput, toInput, '#C6C6C6', '#25daa5', controlSlider);
            setToggleAccessible(toInput);
            if (from <= to) {
                toSlider.value = to;
                toInput.value = to;
            } else {
                toInput.value = from;
            }
        }

        function controlFromSlider(fromSlider, toSlider, fromInput) {
            const [from, to] = getParsed(fromSlider, toSlider);
            fillSlider(fromSlider, toSlider, '#C6C6C6', '#25daa5', toSlider);
            if (from > to) {
                fromSlider.value = to;
                fromInput.value = to;
            } else {
                fromInput.value = from;
            }
        }

        function controlToSlider(fromSlider, toSlider, toInput) {
            const [from, to] = getParsed(fromSlider, toSlider);
            fillSlider(fromSlider, toSlider, '#C6C6C6', '#25daa5', toSlider);
            setToggleAccessible(toSlider);
            if (from <= to) {
                toSlider.value = to;
                toInput.value = to;
            } else {
                toInput.value = from;
                toSlider.value = from;
            }
        }

        function getParsed(currentFrom, currentTo) {
            const from = parseInt(currentFrom.value, 10);
            const to = parseInt(currentTo.value, 10);
            return [from, to];
        }

        function fillSlider(from, to, sliderColor, rangeColor, controlSlider) {
            const rangeDistance = to.max - to.min;
            const fromPosition = from.value - to.min;
            const toPosition = to.value - to.min;
            controlSlider.style.background = `linear-gradient(
              to right,
              ${sliderColor} 0%,
              ${sliderColor} ${(fromPosition) / (rangeDistance) * 100}%,
              ${rangeColor} ${((fromPosition) / (rangeDistance)) * 100}%,
              ${rangeColor} ${(toPosition) / (rangeDistance) * 100}%,
              ${sliderColor} ${(toPosition) / (rangeDistance) * 100}%,
              ${sliderColor} 100%)`;
        }

        function setToggleAccessible(currentTarget) {
            const toSlider = document.querySelector('#toSlider');
            if (Number(currentTarget.value) <= 0) {
                toSlider.style.zIndex = 2;
            } else {
                toSlider.style.zIndex = 0;
            }
        }

        const fromSlider = document.querySelector('#fromSlider');
        const toSlider = document.querySelector('#toSlider');
        const fromInput = document.querySelector('#fromInput');
        const toInput = document.querySelector('#toInput');
        fillSlider(fromSlider, toSlider, '#C6C6C6', '#25daa5', toSlider);
        setToggleAccessible(toSlider);

        fromSlider.oninput = () => controlFromSlider(fromSlider, toSlider, fromInput);
        toSlider.oninput = () => controlToSlider(fromSlider, toSlider, toInput);
        fromInput.oninput = () => controlFromInput(fromSlider, fromInput, toInput, toSlider);
        toInput.oninput = () => controlToInput(toSlider, fromInput, toInput, toSlider);
    </script>
</section>