Manero/ViewModels/UserProfileViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Manero.ViewModels
{
    public class UserProfileViewModel
    {
        public string? FirstName { get; set; } = null!;
        public string? LastName { get; set; } = null!;
        public string? Email { get; set; } = null;
        public string? Phone { get; set; }
        public string? Location { get; set; }
        public string? ImageUrl { get; set; } = null;



        [Display(Name = "Product Image")]
        [DataType(DataType.Upload)]
        public IFormFile? Image { get; set; }


        [Required(ErrorMessage = "Title is required")]
        [Display(Name = "Title")]
        public string? AddressCategory { get; set; }

        [Required(ErrorMessage = "Street name is required")]
        [Display(Name = "Street name")]
        public string? StreetName { get; set; }

        [Required(ErrorMessage = "Street number is required")]
        [Display(Name = "Street number")]
        public string? StreetNumber { get; set; }


        [Required(ErrorMessage = "City is required")]
        [Display(Name = "City")]
        public string? City { get; set; }

    }
}

Manero/Controllers/SignOutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Manero.Controllers
{
    public class SignOutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Manero/Controllers/UserProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace Manero.Controllers
{
    public class UserProfileController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }



        public IActionResult UserAddress()
        {
            return View();
        }        
        


        public IActionResult UserAddressAdd()
        {
            return View();
        }



        public IActionResult UserOrderHistory()
        {
            return View();
        }



        public IActionResult UserPaymentMethods()
        {
            return View();
        }



        public IActionResult UserPaymentMethodAdd()
        {
            return View();
        }



        public IActionResult UserProfileEdit()
        {
            return View();
        }



        public IActionResult UserPromoCodes()
        {
            return View();
        }
    }
}

Manero/Views/UserProfile/Index.cshtml
@using Manero.ViewModels;
@model Manero.ViewModels.UserProfileViewModel

@{
    ViewData["Title"] = "User Profile";


//placeholder
var placeholderUser = new UserProfileViewModel()
        {
            FirstName = "Kristin",
            LastName = "Watson",
            ImageUrl = "/static-images/pexels-andrea-piacquadio-733872.jpg"
        };

}


<!-- part by: christian -->

<head>
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
</head>

<section class="user-profile">
    <div class="container pt-5">
        <div class="frame">
            <div class="presentation">
                <div class="line-container">
                    <div class="left"></div>
                    <div class="right"></div>
                </div>
                <div class="frame">

                    <img src=@placeholderUser.ImageUrl />

                    <div class="frame-icon">
                        <a asp-controller="UserProfile" asp-action="UserProfileEdit"><i class="fa-solid fa-pen-to-square"></i></a>
                    </div>
                </div>
                <h5>@placeholderUser.FirstName @placeholderUser.LastName</h5>
                <h6>@placeholderUser.Email</h6>
            </div>
            <div class="navigation-fields">
                <a class="navigation-field" asp-controller="UserProfile" asp-action="UserAddress">
                    <div class="left">
                        <i class="fa-solid fa-gift"></i>
                        <div class="label">My address</div>
                    </div>
                    <i class="fa-solid fa-chevron-right"></i>
                </a>
                <a class="navigation-field" asp-controller="UserProfile" asp-action="UserOrderHistory">
                    <div class="left">
                        <i class="fa-solid fa-gift"></i>
                        <div class="label">Order history</div>
                    </div>
                    <i class="fa-solid fa-chevron-right"></i>
                </a>
                <a class="navigation-field" asp-controller="UserProfile" asp-action="UserPaymentMethods">
                    <div class="left">
                        <i class="fa-solid fa-gift"></i>
                        <div class="label">Payment method</div>
                    </div>
                    <i class="fa-solid fa-chevron-right"></i>
                </a>

                <a class="navigation-field" asp-controller="UserProfile" asp-action="UserPromoCodes">
                    <div class="left">
                        <i class="fa-solid fa-gift"></i>
                        <div class="label">My promocodes</div>
                    </div>
                    <i class="fa-solid fa-chevron-right"></i>
                </a>
                <a class="navigation-field" asp-controller="SignOut" asp-action="Index">
                    <div class="left">
                        <i class="fa-solid fa-gift"></i>
                        <div class="label">Sign out</div>
                    </div>
                    <div></div>
                </a>
            </div>
        </div>
    </div>
</section>

Manero/Views/UserProfile/UserAddress.cshtml
@using Manero.ViewModels
@model Manero.ViewModels.UserProfileViewModel

@{
    ViewData["Title"] = "My address";


    // placeholder
    var homeAddress = new UserProfileViewModel() {
        AddressCategory = "Home",
        StreetNumber = "8000",
        StreetName = "S. Kirkland Ave",
        City = "Chicago"
    };
    var workAddress = new UserProfileViewModel() {
        AddressCategory = "Work",
        StreetNumber = "500",
        StreetName = "E. Burlington St",
        City = "Chicago"
    };
    var otherAddress = new UserProfileViewModel() {
                AddressCategory = "Home",
                StreetNumber = "900",
                StreetName = "Des Plaines Ave",
                City = "Chicago"
    };
}




<head>
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
</head>

<section class="myaddress-section">

    <!-- added for navigation / christian -->

    <div class="container">
        <div class="navigation-header">
            <a asp-controller="UserProfile" asp-action="Index"><i class="fa-solid fa-chevron-left"></i></a>
            <h5>@ViewData["Title"]</h5>
            <div></div>
        </div>

        <div class="flex-container">



            <partial name="/Views/Partials/UserProfilePartials/_UserAddressPartial.cshtml" model="homeAddress"/>
            <partial name="/Views/Partials/UserProfilePartials/_UserAddressPartial.cshtml" model="workAddress" />
            <partial name="/Views/Partials/UserProfilePartials/_UserAddressPartial.cshtml" model="otherAddress" />



            <a asp-controller="userprofile" asp-action="useraddressadd" class="add mt-5">
                <div class="plus"><i class="fa-regular fa-plus"></i></div>
                <div class="add-address">
                    <p>Add a new address</p>
                </div>
            </a>

        </div>

    </div>
</section>

Manero/Views/UserProfile/UserAddressAdd.cshtml
@using Manero.ViewModels;
@model Manero.ViewModels.UserProfileViewModel

@{
    ViewData["Title"] = "Add new address";
}

<section class="add-address">

    <div class="container">
        <div class="navigation-header">
            <a asp-controller="UserProfile" asp-action="UserAddress"><i class="fa-solid fa-chevron-left"></i></a>
            <h5>@ViewData["Title"]</h5>
            <div></div>
        </div>
    </div>
    <div class="body-frame">
        <div class="address-container">
            <div class="center-content">
                <div class="top-page"></div>

                <div class="container">
                    <form class="mt-5" method="post" novalidate>
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        
                        <!--
                        <div class="input-title">
                            <p>TITLE</p>
                        </div>
                        <input type="text" placeholder="Mom">
                        <div class="input-address"><p>ENTER A NEW ADDRESS</p></div>
                        -->

                        <div class="input-container">
                            <label asp-for="AddressCategory" class="label-text"></label>
                            <input asp-for="AddressCategory" value="" />
                        </div>

                        <div class="input-container">
                            <label asp-for="StreetName" class="label-text"></label>
                            <input asp-for="StreetName" value="" />
                        </div>                   
                        
                        <div class="input-container">
                            <label asp-for="StreetNumber" class="label-text"></label>
                            <input asp-for="StreetNumber" value="" />
                        </div>                   
                        
                        <div class="input-container">
                            <label asp-for="City" class="label-text"></label>
                            <input asp-for="City" value="" />
                        </div>

                        <!--
                        <input type="text" placeholder="3646 S 58th Ave, Cicero, IL 60804, U...">
                        <label class="custom-checkbox">
                        -->

                            <input type="checkbox">
                            <span class="checkmark"></span>
                            Use current location.
                        </label>
                        <button type="submit">SAVE ADDRESS</button>
                    </form>
                </div>

                <div class="black-line"></div>
            </div>
        </div>
    </div>
</section>

Manero/Views/UserProfile/UserOrderHistory.cshtml
@using Manero.ViewModels
@model Manero.ViewModels.OrderViewModel

<!-- part by: christian -->
@{
    ViewData["Title"] = "Order history";



    //placeholder
    var placeholderOrder = new OrderViewModel()
            {
                OrderNumber = 123456,
                OrderDate = DateTime.Now.AddDays(-2),
                OrderStatus = "Delivered",
                OrderTotal = 354.32M,

                OrderItem = "Kids Red Hoodie, S, pink",
                OrderItemQuantity = 1,
                OrderItemPrice = 34.95M
            };
}

<section class="order-history ps-5">

    <div class="container">
        <div class="navigation-header">
            <a class="" asp-controller="UserProfile" asp-action="Index">
                <i class="fa-solid fa-chevron-left"></i></a>
            <h5>@ViewData["Title"]</h5>
            <div></div>
        </div>



        <partial name="/Views/Partials/UserProfilePartials/_UserOrderHistoryPartial.cshtml" model="placeholderOrder" />


        
    </div>
</section>

Manero/Views/UserProfile/UserPaymentMethodAdd.cshtml
@model Manero.ViewModels.PaymentCardAddViewModel

@{
    ViewData["Title"] = "Add new card";

    string placeholderName = "Firstname Lastname";
    string placeholderNumber = "1111 2222 3333 4444";
    string placeholderDate = "00/00";
    string placeholderCode = "123";
}


<section class="edit-card-header container">
    <div class="_title">
        <a asp-controller="UserProfile" asp-action="UserPaymentMethods"><i class="fa-solid fa-chevron-left"></i></a>
        <h5>@ViewData["Title"]</h5>
        <div></div>
    </div>
</section>

<section class="edit-card container">

    <div class="vertical-line"></div>
    <div class="d-flex justify-content-center">
        <div class="_card mt-3">
            <img src="/static-images/paymentcard.png" />
            <i class="fa-brands fa-cc-visa"></i>
            <p class="card-number">@placeholderNumber</p>
            <p class="card-name">@placeholderName</p>
            <p class="expire">@placeholderDate</p>
        </div>
    </div>


</section>

<section class="card-details container">
    <form class="mb-3" method="post" novalidate>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="field-div mt-5">
            <label asp-for="CardHolderName" class="label-text"></label>
            <input asp-for="CardHolderName" value=@placeholderName />
        </div>
        <div class="d-flex justify-content-between card-number">
            <div class="field-div">
                <label asp-for="CardNumber" class="label-text"></label>
                <input asp-for="CardNumber" value=@placeholderNumber />
            </div>
            <button><i class="fa-light fa-camera"></i></button>
        </div>

        <div class="d-flex">
            <div class="field-div">
                <label asp-for="CardExpirationDate" class="label-text"></label>
                <input asp-for="CardExpirationDate" value=@placeholderDate />
            </div>
            <div class="field-div">
                <label asp-for="CardCVV" class="label-text"></label>
                <input asp-for="CardCVV" type="password" value=@placeholderCode />
            </div>
        </div>


        <button type="submit" class="black-button mt-5">SAVE CARD</button>
    </form>
</section>

Manero/Views/UserProfile/UserPaymentMethods.cshtml
@using Manero.ViewModels
@model Manero.ViewModels.PaymentMethodViewModel

@{
    ViewData["Title"] = "Payment methods";

    var currentUser = new PaymentMethodViewModel()
    {
        PaymentMethodCard = true,
        CardType = "fa-cc-visa",
        CardHolderName = "Kristin Watson",
        CardNumber = "7741 6588 2123 6644",
        CardExpirationDate = "07/27",

        PaymentMethodApplePay = true,
        PaymentMethodPayPal = true,
        PaymentMethodPayoneer = false,
    };
}

<head>
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
</head>

<section class="payment-header container">
    <div class="navigation-header">
        <a asp-controller="UserProfile" asp-action="Index"><i class="fa-solid fa-chevron-left"></i></a>
        <h5>@ViewData["Title"]</h5>
        <div></div>
    </div>
</section>

<section class="saved-cards container">
    <div class="d-flex justify-content-between">
        <div>Cards</div>
        <a class="add-card" asp-controller="UserProfile" asp-action="UserPaymentMethodAdd">Add a new card<i class="fa-light fa-plus ms-4"></i></a>
    </div>

    <div class="slider">


        <partial name="/Views/Partials/PaymentMethodPartials/_PaymentCard.cshtml" model="currentUser" />
        <partial name="/Views/Partials/PaymentMethodPartials/_PaymentCard.cshtml" model="currentUser" />
        <partial name="/Views/Partials/PaymentMethodPartials/_PaymentCard.cshtml" model="currentUser" />


    </div>
</section>

<section class="payment-methods container">

        <div class="d-flex justify-content-between">
        @if (currentUser.PaymentMethodApplePay == true)
        {
            <p class="_name">Apple Pay<i class="fa-solid fa-check ms-3"></i></p>
            <a href="" class="edit-or-add"><i class="fa-light fa-pen-to-square"></i></a>
        } else {
            <p class="_name">Apple Pay</p>
            <a href="" class="edit-or-add"><i class="fa-light fa-plus ms-4"></i></a>
        }
        </div>

        <div class="d-flex justify-content-between">
        @if (currentUser.PaymentMethodPayPal == true)
        {
            <p class="_name">Pay Pal<i class="fa-solid fa-check ms-3"></i></p>
            <a href="" class="edit-or-add"><i class="fa-light fa-pen-to-square"></i></a>
        }
        else {
            <p class="_name">Pay Pal</p>
            <a href="" class="edit-or-add"><i class="fa-light fa-plus ms-4"></i></a>
        }
        </div>
        <div class="d-flex justify-content-between">
        @if (currentUser.PaymentMethodPayoneer == true)
        {
            <p class="_name">Payoneer<i class="fa-solid fa-check ms-3"></i></p>
            <a href="" class="edit-or-add"><i class="fa-light fa-pen-to-square"></i></a>
        }
        else {
            <p class="_name">Payoneer</p>
            <a href="" class="edit-or-add"><i class="fa-light fa-plus ms-4"></i></a>
        }
        </div>
</section>

<script>
    function controlFromInput(fromSlider, fromInput, toInput, controlSlider) {
        const [from, to] = getParsed(fromInput, toInput);
        fillSlider(fromInput, toInput, '#C6C6C6', '#111111', controlSlider);
        if (from > to) {
            fromSlider.value = to;
            fromInput.value = to;
        } else {
            fromSlider.value = from;
        }
    }

    function controlToInput(toSlider, fromInput, toInput, controlSlider) {
        const [from, to] = getParsed(fromInput, toInput);
        fillSlider(fromInput, toInput, '#C6C6C6', '#111111', controlSlider);
        setToggleAccessible(toInput);
        if (from <= to) {
            toSlider.value = to;
            toInput.value = to;
        } else {
            toInput.value = from;
        }
    }

    function controlFromSlider(fromSlider, toSlider, fromInput) {
        const [from, to] = getParsed(fromSlider, toSlider);
        fillSlider(fromSlider, toSlider, '#C6C6C6', '#111111', toSlider);
        if (from > to) {
            fromSlider.value = to;
            fromInput.value = to;
        } else {
            fromInput.value = from;
        }
    }

    function controlToSlider(fromSlider, toSlider, toInput) {
        const [from, to] = getParsed(fromSlider, toSlider);
        fillSlider(fromSlider, toSlider, '#C6C6C6', '#111111', toSlider);
        setToggleAccessible(toSlider);
        if (from <= to) {
            toSlider.value = to;
            toInput.value = to;
        } else {
            toInput.value = from;
            toSlider.value = from;
        }
    }

    function getParsed(currentFrom, currentTo) {
        const from = parseInt(currentFrom.value, 10);
        const to = parseInt(currentTo.value, 10);
        return [from, to];
    }

    function fillSlider(from, to, sliderColor, rangeColor, controlSlider) {
        const rangeDistance = to.max - to.min;
        const fromPosition = from.value - to.min;
        const toPosition = to.value - to.min;
        controlSlider.style.background = `linear-gradient(
              to right,
              ${sliderColor} 0%,
              ${sliderColor} ${(fromPosition) / (rangeDistance) * 100}%,
              ${rangeColor} ${((fromPosition) / (rangeDistance)) * 100}%,
              ${rangeColor} ${(toPosition) / (rangeDistance) * 100}%,
              ${sliderColor} ${(toPosition) / (rangeDistance) * 100}%,
              ${sliderColor} 100%)`;
    }

    function setToggleAccessible(currentTarget) {
        const toSlider = document.querySelector('#toSlider');
        if (Number(currentTarget.value) <= 0) {
            toSlider.style.zIndex = 2;
        } else {
            toSlider.style.zIndex = 0;
        }
    }

    const fromSlider = document.querySelector('#fromSlider');
    const toSlider = document.querySelector('#toSlider');
    const fromInput = document.querySelector('#fromInput');
    const toInput = document.querySelector('#toInput');
    fillSlider(fromSlider, toSlider, '#C6C6C6', '#111111', toSlider);
    setToggleAccessible(toSlider);

    fromSlider.oninput = () => controlFromSlider(fromSlider, toSlider, fromInput);
    toSlider.oninput = () => controlToSlider(fromSlider, toSlider, toInput);
    fromInput.oninput = () => controlFromInput(fromSlider, fromInput, toInput, toSlider);
    toInput.oninput = () => controlToInput(toSlider, fromInput, toInput, toSlider);

</script>

Manero/Views/UserProfile/UserProfileEdit.cshtml
@using Manero.ViewModels;
@model Manero.ViewModels.UserProfileViewModel

<!-- part by: christian -->
@{
    ViewData["Title"] = "Edit profile";

    var placeholderUser = new UserProfileViewModel
    {
        ImageUrl = "/static-images/pexels-andrea-piacquadio-733872.jpg"
    };
}



<section class="user-profile">
    <div class="container">

        <div class="navigation-header">
            <a asp-controller="UserProfile" asp-action="Index"><i class="fa-solid fa-chevron-left"></i></a>
            <h5>@ViewData["Title"]</h5>
            <div></div>
        </div>

        <div class="frame">
            <div class="presentation">
                <div class="line-container">
                    <div class="left"></div>
                    <div class="right"></div>
                </div>
                <div class="frame">
                    <img src=@placeholderUser.ImageUrl />
                    <div class="frame-icon">
                        <a asp-controller="UserProfile" asp-action="UserProfileEdit"><i class="fa-solid fa-pen-to-square"></i></a>
                    </div>
                </div>
            </div>

            <form class="" method="post" novalidate>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="my-3">
                    <label asp-for="FirstName" class="label-text"></label>
                    <input asp-for="FirstName" value="" />
                </div>
                <div class="my-3">
                    <label asp-for="LastName" class="label-text"></label>
                    <input asp-for="LastName" value="" />
                </div>
                <div class="my-3">
                    <label asp-for="Email" class="label-text"></label>
                    <input asp-for="Email" value="" />
                </div>
                <div class="my-3">
                    <label asp-for="Phone" class="label-text"></label>
                    <input asp-for="Phone" value="" />
                </div>
                <div class="my-3">
                    <label asp-for="Location" class="label-text"></label>
                    <input asp-for="Location" value="" />
                </div>

                <button input type="submit" value="Submit">SUBMIT</button>
            </form>


        </div>
    </div>
</section>
 

Manero/Views/UserProfile/UserPromoCodes.cshtml
@using Manero.ViewModels
@model Manero.ViewModels.PromoCodeViewModel

@{
    ViewData["Title"] = "My Promo codes";

    // placeholder
    var acme = new PromoCodeViewModel()
            {
                ImageUrl = "/static-images/placeholder_promocode.svg",
                Title = "Acme Co.",
                Discount = 50,
                ExpirationDate = "June 30, 2022",
            };
    var barone = new PromoCodeViewModel()
            {
                ImageUrl = "/static-images/placeholder_promocode.svg",
                Title = "Barone LLC.",
                Discount = 30,
                ExpirationDate = "June 30, 2022",
            };
    var abstergo = new PromoCodeViewModel()
            {
                ImageUrl = "/static-images/placeholder_promocode.svg",
                Title = "Abstergo Ltd.",
                Discount = 15,
                ExpirationDate = "June 30, 2022",
            };
}

<section class="promocodes-header container">
    <div class="_title">
        <a asp-controller="UserProfile" asp-action="Index"><i class="fa-solid fa-chevron-left"></i></a>
        <h5>@ViewData["Title"]</h5>
        <div></div>
    </div>
    <div class="buttons">
        <button class="_active">Current</button>
        <button>Used</button>
    </div>
</section>

<section class="my-promocodes container">
    <hr />

    <partial name="/Views/Partials/UserProfilePartials/_UserPromoCodePartial.cshtml" model="acme" />
    <partial name="/Views/Partials/UserProfilePartials/_UserPromoCodePartial.cshtml" model="barone" />    
    <partial name="/Views/Partials/UserProfilePartials/_UserPromoCodePartial.cshtml" model="abstergo" />

</section>

<section class="no-promocodes container d-none">
    <img src="/images/promocode_img.svg" />
    <div class="vertical-line"></div>
    <h4>Your don’t have promocodes yet!</h4>
    <p>Qui ex aute ipsum duis. Incididunt adipisicing voluptate laborum</p>
    <div class="input-title">
        <p>ENTER THE VOUCHER</p>
    </div>
    <input type="text" />
    <div>
        <button class="black-button">SUBMIT</button>
    </div>


</section>